### ISSUE TITLE
Vẽ biểu đồ UML, từ điển thuật ngữ, đặc tả phụ trợ, phân công công việc

### ISSUE THREAD

**Issue by anhthanhnien** [anhthanhnien/2019_2_PTTKPM_Group02#2]

**Comment by NguyenTrongCuong** [comment]
Biểu đồ UML: 
[usecasediagram.pdf](https://github.com/anhthanhnien/2019_2_PTTKPM_Group02/files/4449142/usecasediagram.pdf)
Đặc tả phụ trợ: 
[dactaphutro.docx](https://github.com/anhthanhnien/2019_2_PTTKPM_Group02/files/4449145/dactaphutro.docx)
Đặc tả use case: 
[dactausecase.docx](https://github.com/anhthanhnien/2019_2_PTTKPM_Group02/files/4449149/dactausecase.docx)
Từ điển thuật ngữ: 
[tudienthuatngu.docx](https://github.com/anhthanhnien/2019_2_PTTKPM_Group02/files/4449150/tudienthuatngu.docx)
